# Generated by Django 2.2.16 on 2022-09-15 07:49

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="rating",
            new_name="score",
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[reviews.validators.validate_username],
            ),
        ),
    ]
